// Recepty: makra jsou na 1 porci, suroviny také na 1 porci.
// cat: kategorie suroviny pro nákupní seznam
// shop: kde se to nejlíp kupuje (orientační)

const M = "Maso a ryby";
const D = "Mléčné a vejce";
const Z = "Zelenina a ovoce";
const T = "Trvanlivé";
const P = "Pečivo";
const O = "Ostatní";

export const RECIPES = [
  // ---------- SNÍDANĚ ----------
  {
    id: "b1",
    typ: "snidane",
    nazev: "Řecký jogurt s pistáciemi a medem",
    cas: 5,
    kcal: 430, bilkoviny: 34, sacharidy: 34, tuky: 17,
    shop: "Lidl",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 250, u: "g", cat: D },
      { n: "Pistácie nesolené", q: 15, u: "g", cat: T },
      { n: "Med", q: 10, u: "g", cat: T },
      { n: "Borůvky", q: 80, u: "g", cat: Z },
      { n: "Ovesné vločky", q: 30, u: "g", cat: T },
    ],
    postup: [
      "Vločky krátce opraž nasucho na pánvi, než začnou vonět.",
      "Jogurt dej do misky, zamíchej med.",
      "Navrch vločky, borůvky a nasekané pistácie.",
    ],
  },
  {
    id: "b2",
    typ: "snidane",
    nazev: "Šakšuka s fetou",
    cas: 20,
    kcal: 470, bilkoviny: 30, sacharidy: 28, tuky: 26,
    shop: "Rohlík",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Krájená rajčata konzerva", q: 200, u: "g", cat: T },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Na oleji zesklovatěj cibuli s paprikou, 6 minut.",
      "Přidej rajčata, mletou papriku a kmín, vař 8 minut do zhoustnutí.",
      "Udělej důlky, rozklepni vejce, přiklop a táhni 5 minut.",
      "Posyp fetou, podávej s chlebem.",
    ],
  },
  {
    id: "b3",
    typ: "snidane",
    nazev: "Omeleta se špenátem a cottage",
    cas: 12,
    kcal: 400, bilkoviny: 38, sacharidy: 20, tuky: 19,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Bílky (nebo vejce navíc)", q: 100, u: "g", cat: D },
      { n: "Špenát čerstvý", q: 80, u: "g", cat: Z },
      { n: "Cottage sýr", q: 100, u: "g", cat: D },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: [
      "Na oleji zavadni špenát, osol, opepři.",
      "Zalij rozšlehanými vejci s bílky, táhni na mírném ohni.",
      "Na půlku dej cottage, přehni a podávej s chlebem.",
    ],
  },
  {
    id: "b4",
    typ: "snidane",
    nazev: "Tvarohový krém s pomerančem a mandlemi",
    cas: 5,
    kcal: 410, bilkoviny: 40, sacharidy: 35, tuky: 12,
    shop: "Lidl",
    suroviny: [
      { n: "Tvaroh polotučný", q: 250, u: "g", cat: D },
      { n: "Pomeranč", q: 1, u: "ks", cat: Z },
      { n: "Mandle", q: 15, u: "g", cat: T },
      { n: "Med", q: 8, u: "g", cat: T },
      { n: "Ovesné vločky", q: 25, u: "g", cat: T },
    ],
    postup: [
      "Tvaroh rozmíchej s medem a lžící vody do hladka.",
      "Přidej filety z pomeranče, vločky a sekané mandle.",
    ],
  },
  {
    id: "b5",
    typ: "snidane",
    nazev: "Celozrnný toast s avokádem a vejci",
    cas: 10,
    kcal: 490, bilkoviny: 27, sacharidy: 38, tuky: 25,
    shop: "Rohlík",
    suroviny: [
      { n: "Chléb celozrnný", q: 80, u: "g", cat: P },
      { n: "Avokádo", q: 0.5, u: "ks", cat: Z },
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Rajčata cherry", q: 80, u: "g", cat: Z },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
      { n: "Cottage sýr", q: 60, u: "g", cat: D },
    ],
    postup: [
      "Vejce uvař 7 minut, zchlaď a oloupej.",
      "Avokádo rozmačkej s citronem a solí, natři na opečený chléb.",
      "Navrch cottage, půlky cherry rajčat a vejce.",
    ],
  },
  {
    id: "b6",
    typ: "snidane",
    nazev: "Ovesná kaše s jogurtem a lesním ovocem",
    cas: 10,
    kcal: 450, bilkoviny: 33, sacharidy: 52, tuky: 12,
    shop: "Lidl",
    suroviny: [
      { n: "Ovesné vločky", q: 60, u: "g", cat: T },
      { n: "Mléko polotučné", q: 200, u: "ml", cat: D },
      { n: "Řecký jogurt 2 %", q: 150, u: "g", cat: D },
      { n: "Mražené lesní ovoce", q: 100, u: "g", cat: Z },
      { n: "Vlašské ořechy", q: 10, u: "g", cat: T },
      { n: "Skořice", q: 1, u: "g", cat: T },
    ],
    postup: [
      "Vločky vař v mléce 5 minut se špetkou soli a skořicí.",
      "Ovoce prohřej zvlášť, aby pustilo šťávu.",
      "Kaši zakápni jogurtem, přidej ovoce a ořechy.",
    ],
  },

  // ---------- SVAČINY ----------
  {
    id: "s1",
    typ: "svacina",
    nazev: "Cottage s olivami a okurkou",
    cas: 3,
    kcal: 250, bilkoviny: 24, sacharidy: 12, tuky: 11,
    shop: "Lidl",
    suroviny: [
      { n: "Cottage sýr", q: 180, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Knäckebrot žitný", q: 20, u: "g", cat: P },
    ],
    postup: ["Cottage smíchej s nakrájenou okurkou a olivami, opepři, jez s knäckebrotem."],
  },
  {
    id: "s2",
    typ: "svacina",
    nazev: "Hummus s mrkví a pita chlebem",
    cas: 5,
    kcal: 300, bilkoviny: 13, sacharidy: 36, tuky: 12,
    shop: "Rohlík",
    suroviny: [
      { n: "Hummus", q: 80, u: "g", cat: T },
      { n: "Mrkev", q: 120, u: "g", cat: Z },
      { n: "Pita celozrnná", q: 60, u: "g", cat: P },
    ],
    postup: ["Mrkev nakrájej na hranolky, pitu opeč a natrhej."],
  },
  {
    id: "s3",
    typ: "svacina",
    nazev: "Skyr s ořechy a jablkem",
    cas: 2,
    kcal: 280, bilkoviny: 28, sacharidy: 26, tuky: 8,
    shop: "Lidl",
    suroviny: [
      { n: "Skyr přírodní", q: 200, u: "g", cat: D },
      { n: "Jablko", q: 1, u: "ks", cat: Z },
      { n: "Mandle", q: 12, u: "g", cat: T },
    ],
    postup: ["Skyr smíchej s nastrouhaným jablkem a mandlemi."],
  },
  {
    id: "s4",
    typ: "svacina",
    nazev: "Tuňákový salát v listech salátu",
    cas: 6,
    kcal: 260, bilkoviny: 30, sacharidy: 8, tuky: 12,
    shop: "Makro",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 120, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 50, u: "g", cat: D },
      { n: "Salát ledový / římský", q: 80, u: "g", cat: Z },
      { n: "Červená cibule", q: 20, u: "g", cat: Z },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: ["Tuňáka slij, smíchej s jogurtem, cibulí a citronem. Nandej do listů salátu."],
  },
  {
    id: "s5",
    typ: "svacina",
    nazev: "Kefír, pomeranč a hrst vlašských ořechů",
    cas: 2,
    kcal: 290, bilkoviny: 16, sacharidy: 28, tuky: 14,
    shop: "Lidl",
    suroviny: [
      { n: "Kefír / acidofilní mléko", q: 300, u: "ml", cat: D },
      { n: "Pomeranč", q: 1, u: "ks", cat: Z },
      { n: "Vlašské ořechy", q: 20, u: "g", cat: T },
    ],
    postup: ["Nic se nevaří. Jen nezapomeň, že ořechy jsou kalorická bomba — važ je."],
  },
  {
    id: "s6",
    typ: "svacina",
    nazev: "Řecký jogurt s cizrnovými chipsy",
    cas: 4,
    kcal: 270, bilkoviny: 25, sacharidy: 24, tuky: 8,
    shop: "Rohlík",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 200, u: "g", cat: D },
      { n: "Cizrna konzerva", q: 80, u: "g", cat: T },
      { n: "Olivový olej", q: 3, u: "ml", cat: T },
      { n: "Rajčata cherry", q: 80, u: "g", cat: Z },
    ],
    postup: [
      "Cizrnu osuš, zakápni olejem, opeč 15 minut na 200 °C do křupava.",
      "Jogurt osol, opepři, navrch cizrna a rajčata.",
    ],
  },

  // ---------- OBĚDY ----------
  {
    id: "o1",
    typ: "obed",
    nazev: "Kuřecí souvlaki s bulgurem a tzatziki",
    cas: 30,
    kcal: 620, bilkoviny: 55, sacharidy: 55, tuky: 19,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Bulgur", q: 70, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Okurka salátová", q: 80, u: "g", cat: Z },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Kuře nakrájej na kostky, marinuj v oleji, citronu, oreganu a česneku (klidně přes noc).",
      "Bulgur zalij vroucí vodou 1:2, přiklop na 15 minut.",
      "Kuře opeč na rozpálené pánvi 8 minut dokřupava.",
      "Tzatziki: nastrouhanou vymačkanou okurku smíchej s jogurtem a česnekem.",
    ],
  },
  {
    id: "o2",
    typ: "obed",
    nazev: "Losos s quinoou a pečenou zeleninou",
    cas: 35,
    kcal: 650, bilkoviny: 45, sacharidy: 48, tuky: 28,
    shop: "Rohlík",
    suroviny: [
      { n: "Losos filet", q: 160, u: "g", cat: M },
      { n: "Quinoa", q: 60, u: "g", cat: T },
      { n: "Cuketa", q: 120, u: "g", cat: Z },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 40, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: [
      "Zeleninu nakrájej na větší kusy, promíchej s olejem a solí, peč 20 minut na 200 °C.",
      "Quinou propláchni a vař 12 minut ve dvojnásobku vody.",
      "Lososa přidej k zelenině na posledních 12 minut, kůží nahoru.",
      "Zakápni citronem.",
    ],
  },
  {
    id: "o3",
    typ: "obed",
    nazev: "Gyros bowl s cizrnou a fetou",
    cas: 25,
    kcal: 640, bilkoviny: 52, sacharidy: 52, tuky: 22,
    shop: "Lidl",
    suroviny: [
      { n: "Kuřecí stehenní maso bez kosti", q: 170, u: "g", cat: M },
      { n: "Cizrna konzerva", q: 150, u: "g", cat: T },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Okurka salátová", q: 80, u: "g", cat: Z },
      { n: "Feta", q: 30, u: "g", cat: D },
      { n: "Rýže basmati", q: 40, u: "g", cat: T },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Gyros koření", q: 5, u: "g", cat: T },
    ],
    postup: [
      "Maso nakrájej na nudličky, obal v koření, opeč dosucha na pánvi.",
      "Rýži uvař, cizrnu prohřej s masem na konci.",
      "Do misky rýže, maso, syrová zelenina, feta.",
    ],
  },
  {
    id: "o4",
    typ: "obed",
    nazev: "Fazolový salát s tuňákem a vejcem",
    cas: 15,
    kcal: 560, bilkoviny: 48, sacharidy: 42, tuky: 20,
    shop: "Makro",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 140, u: "g", cat: T },
      { n: "Bílé fazole konzerva", q: 180, u: "g", cat: T },
      { n: "Vejce M", q: 1, u: "ks", cat: D },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Petržel natě", q: 10, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Fazole propláchni, smíchej s tuňákem, rajčaty a cibulí.",
      "Zalij olejem s citronem, přidej petržel.",
      "Navrch půlené vejce, k tomu chléb.",
    ],
  },
  {
    id: "o5",
    typ: "obed",
    nazev: "Krevety s cizrnovým salátem a fetou",
    cas: 20,
    kcal: 570, bilkoviny: 46, sacharidy: 40, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Krevety loupané mražené", q: 200, u: "g", cat: M },
      { n: "Cizrna konzerva", q: 160, u: "g", cat: T },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Krevety rozmrazené osuš, opeč na oleji s česnekem 3 minuty z každé strany.",
      "Smíchej s cizrnou a rajčaty, zakápni citronem, rozdrob fetu.",
    ],
  },
  {
    id: "o6",
    typ: "obed",
    nazev: "Celozrnné těstoviny s tuňákem a olivami",
    cas: 20,
    kcal: 630, bilkoviny: 45, sacharidy: 68, tuky: 18,
    shop: "Lidl",
    suroviny: [
      { n: "Celozrnné těstoviny", q: 80, u: "g", cat: T },
      { n: "Tuňák ve vlastní šťávě", q: 140, u: "g", cat: T },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Parmazán", q: 10, u: "g", cat: D },
    ],
    postup: [
      "Těstoviny vař al dente.",
      "Na oleji orestuj česnek, přidej rajčata a olivy, vař 8 minut.",
      "Vmíchej tuňáka a hotové těstoviny, posyp parmazánem.",
    ],
  },
  {
    id: "o7",
    typ: "obed",
    nazev: "Pečená makrela s bramborem a fazolkami",
    cas: 35,
    kcal: 660, bilkoviny: 44, sacharidy: 45, tuky: 32,
    shop: "Rohlík",
    suroviny: [
      { n: "Makrela celá / filet", q: 200, u: "g", cat: M },
      { n: "Brambory", q: 250, u: "g", cat: Z },
      { n: "Fazolky zelené mražené", q: 150, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Rozmarýn", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Brambory na měsíčky, olej, sůl, rozmarýn — peč 30 minut na 200 °C.",
      "Makrelu osol, naplň citronem, peč posledních 15 minut.",
      "Fazolky vař 5 minut, zakápni olejem.",
    ],
  },
  {
    id: "o8",
    typ: "obed",
    nazev: "Cizrnový salát s grilovaným halloumi",
    cas: 20,
    kcal: 580, bilkoviny: 34, sacharidy: 45, tuky: 28,
    shop: "Lidl",
    suroviny: [
      { n: "Halloumi", q: 100, u: "g", cat: D },
      { n: "Cizrna konzerva", q: 180, u: "g", cat: T },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Olivový olej", q: 6, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Halloumi nakrájej na plátky a opeč nasucho z obou stran.",
      "Zeleninu s cizrnou zamíchej s olejem a citronem, navrch sýr.",
    ],
  },

  // ---------- VEČEŘE ----------
  {
    id: "v1",
    typ: "vecere",
    nazev: "Řecká pečená treska plaki",
    cas: 35,
    kcal: 480, bilkoviny: 48, sacharidy: 30, tuky: 17,
    shop: "Rohlík",
    suroviny: [
      { n: "Treska filet", q: 200, u: "g", cat: M },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Cibule", q: 60, u: "g", cat: Z },
      { n: "Brambory", q: 150, u: "g", cat: Z },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Petržel natě", q: 10, u: "g", cat: Z },
    ],
    postup: [
      "Na oleji zesklovatěj cibuli s česnekem, přidej rajčata, vař 10 minut.",
      "Do zapékací mísy dej tenké plátky brambor, na ně rybu a omáčku.",
      "Peč 25 minut na 190 °C, posyp petrželí.",
    ],
  },
  {
    id: "v2",
    typ: "vecere",
    nazev: "Krůtí kofta s tzatziki a salátem",
    cas: 30,
    kcal: 520, bilkoviny: 52, sacharidy: 24, tuky: 24,
    shop: "Makro",
    suroviny: [
      { n: "Mleté krůtí maso", q: 200, u: "g", cat: M },
      { n: "Řecký jogurt 2 %", q: 120, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Pita celozrnná", q: 30, u: "g", cat: P },
      { n: "Kmín mletý", q: 2, u: "g", cat: T },
      { n: "Olivový olej", q: 6, u: "ml", cat: T },
    ],
    postup: [
      "Maso smíchej s cibulí, kmínem, solí, vytvaruj podlouhlé placky.",
      "Opeč na pánvi 10 minut, průběžně otáčej.",
      "Tzatziki z jogurtu a vymačkané okurky, k tomu salát a kousek pity.",
    ],
  },
  {
    id: "v3",
    typ: "vecere",
    nazev: "Zapečený lilek s mletým hovězím a jogurtem",
    cas: 45,
    kcal: 560, bilkoviny: 46, sacharidy: 26, tuky: 30,
    shop: "Rohlík",
    suroviny: [
      { n: "Mleté hovězí 10 %", q: 180, u: "g", cat: M },
      { n: "Lilek", q: 250, u: "g", cat: Z },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Parmazán", q: 15, u: "g", cat: D },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Skořice", q: 1, u: "g", cat: T },
    ],
    postup: [
      "Lilek na plátky, potři olejem, peč 15 minut na 200 °C.",
      "Maso orestuj s cibulí, přidej rajčata a špetku skořice, vař 10 minut.",
      "Vrstvi lilek a maso, navrch jogurt s parmazánem, zapeč 15 minut.",
    ],
  },
  {
    id: "v4",
    typ: "vecere",
    nazev: "Kuřecí prsa s cuketou, rajčaty a fetou",
    cas: 25,
    kcal: 490, bilkoviny: 54, sacharidy: 16, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 200, u: "g", cat: M },
      { n: "Cuketa", q: 200, u: "g", cat: Z },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
    ],
    postup: [
      "Kuře nařízni na motýlka, osol, opeč 4 minuty z každé strany.",
      "Přidej cuketu na půlměsíčky a rajčata, orestuj 6 minut.",
      "Posyp fetou a oreganem, přiklop na 2 minuty.",
    ],
  },
  {
    id: "v5",
    typ: "vecere",
    nazev: "Krevety saganaki s fetou a rajčaty",
    cas: 25,
    kcal: 450, bilkoviny: 42, sacharidy: 22, tuky: 21,
    shop: "Makro",
    suroviny: [
      { n: "Krevety loupané mražené", q: 200, u: "g", cat: M },
      { n: "Krájená rajčata konzerva", q: 200, u: "g", cat: T },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Na oleji orestuj česnek, přilij rajčata, vař 10 minut.",
      "Vlož krevety, po 4 minutách rozdrob fetu a přiklop.",
      "Vytírej chlebem.",
    ],
  },
  {
    id: "v6",
    typ: "vecere",
    nazev: "Čočka s pečenou zeleninou a sázeným vejcem",
    cas: 35,
    kcal: 520, bilkoviny: 32, sacharidy: 55, tuky: 18,
    shop: "Lidl",
    suroviny: [
      { n: "Čočka beluga / zelená", q: 80, u: "g", cat: T },
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Cuketa", q: 150, u: "g", cat: Z },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 40, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Ocet balsamico", q: 5, u: "ml", cat: T },
    ],
    postup: [
      "Čočku vař 20 minut do měkka, sceď.",
      "Zeleninu peč 20 minut na 200 °C s olejem.",
      "Smíchej, zakápni balsamikem, navrch sázená vejce.",
    ],
  },
  {
    id: "v7",
    typ: "vecere",
    nazev: "Treska se špenátem a bramborovým pyré",
    cas: 30,
    kcal: 500, bilkoviny: 48, sacharidy: 38, tuky: 16,
    shop: "Rohlík",
    suroviny: [
      { n: "Treska filet", q: 200, u: "g", cat: M },
      { n: "Brambory", q: 220, u: "g", cat: Z },
      { n: "Špenát čerstvý", q: 150, u: "g", cat: Z },
      { n: "Mléko polotučné", q: 50, u: "ml", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: [
      "Brambory uvař, rozšťouchej s mlékem a lžičkou oleje.",
      "Rybu osol, opeč 3–4 minuty z každé strany, zakápni citronem.",
      "Špenát krátce zavadni s česnekem.",
    ],
  },
  {
    id: "v8",
    typ: "vecere",
    nazev: "Řecký salát s kuřetem a bílým jogurtem",
    cas: 20,
    kcal: 470, bilkoviny: 50, sacharidy: 18, tuky: 21,
    shop: "Lidl",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Rajčata", q: 150, u: "g", cat: Z },
      { n: "Okurka salátová", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Kuře opeč na grilovací pánvi, nech odpočinout a nakrájej.",
      "Zeleninu nakrájej nahrubo, zalij olejem, posyp oreganem a fetou.",
    ],
  },
];

export const TYPY = {
  snidane: "Snídaně",
  svacina: "Svačina",
  obed: "Oběd",
  vecere: "Večeře",
};

export const byId = (id) => RECIPES.find((r) => r.id === id);
export const byType = (t) => RECIPES.filter((r) => r.typ === t);
