// Recepty: makra jsou na 1 porci, suroviny také na 1 porci.
// cat: kategorie suroviny pro nákupní seznam
// shop: kde se to nejlíp kupuje (orientační)

const M = "Maso a ryby";
const D = "Mléčné a vejce";
const Z = "Zelenina a ovoce";
const T = "Trvanlivé";
const P = "Pečivo";
const O = "Ostatní";

export const RECIPES = [
  // ---------- SNÍDANĚ ----------
  {
    id: "b1",
    typ: "snidane",
    chut: "sladke",
    nazev: "Řecký jogurt s pistáciemi a medem",
    cas: 5,
    kcal: 430, bilkoviny: 34, sacharidy: 34, tuky: 17,
    shop: "Lidl",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 250, u: "g", cat: D },
      { n: "Pistácie nesolené", q: 15, u: "g", cat: T },
      { n: "Med", q: 10, u: "g", cat: T },
      { n: "Borůvky", q: 80, u: "g", cat: Z },
      { n: "Ovesné vločky", q: 30, u: "g", cat: T },
    ],
    postup: [
      "Vločky krátce opraž nasucho na pánvi, než začnou vonět.",
      "Jogurt dej do misky, zamíchej med.",
      "Navrch vločky, borůvky a nasekané pistácie.",
    ],
  },
  {
    id: "b2",
    typ: "snidane",
    chut: "slane",
    nazev: "Šakšuka s fetou",
    cas: 20,
    kcal: 470, bilkoviny: 30, sacharidy: 28, tuky: 26,
    shop: "Rohlík",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Krájená rajčata konzerva", q: 200, u: "g", cat: T },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Na oleji zesklovatěj cibuli s paprikou, 6 minut.",
      "Přidej rajčata, mletou papriku a kmín, vař 8 minut do zhoustnutí.",
      "Udělej důlky, rozklepni vejce, přiklop a táhni 5 minut.",
      "Posyp fetou, podávej s chlebem.",
    ],
  },
  {
    id: "b3",
    typ: "snidane",
    chut: "slane",
    nazev: "Omeleta se špenátem a cottage",
    cas: 12,
    kcal: 400, bilkoviny: 38, sacharidy: 20, tuky: 19,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Bílky (nebo vejce navíc)", q: 100, u: "g", cat: D },
      { n: "Špenát čerstvý", q: 80, u: "g", cat: Z },
      { n: "Cottage sýr", q: 100, u: "g", cat: D },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: [
      "Na oleji zavadni špenát, osol, opepři.",
      "Zalij rozšlehanými vejci s bílky, táhni na mírném ohni.",
      "Na půlku dej cottage, přehni a podávej s chlebem.",
    ],
  },
  {
    id: "b4",
    typ: "snidane",
    chut: "sladke",
    nazev: "Tvarohový krém s pomerančem a mandlemi",
    cas: 5,
    kcal: 410, bilkoviny: 40, sacharidy: 35, tuky: 12,
    shop: "Lidl",
    suroviny: [
      { n: "Tvaroh polotučný", q: 250, u: "g", cat: D },
      { n: "Pomeranč", q: 1, u: "ks", cat: Z },
      { n: "Mandle", q: 15, u: "g", cat: T },
      { n: "Med", q: 8, u: "g", cat: T },
      { n: "Ovesné vločky", q: 25, u: "g", cat: T },
    ],
    postup: [
      "Tvaroh rozmíchej s medem a lžící vody do hladka.",
      "Přidej filety z pomeranče, vločky a sekané mandle.",
    ],
  },
  {
    id: "b5",
    typ: "snidane",
    chut: "slane",
    nazev: "Celozrnný toast s avokádem a vejci",
    cas: 10,
    kcal: 490, bilkoviny: 27, sacharidy: 38, tuky: 25,
    shop: "Rohlík",
    suroviny: [
      { n: "Chléb celozrnný", q: 80, u: "g", cat: P },
      { n: "Avokádo", q: 0.5, u: "ks", cat: Z },
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Rajčata cherry", q: 80, u: "g", cat: Z },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
      { n: "Cottage sýr", q: 60, u: "g", cat: D },
    ],
    postup: [
      "Vejce uvař 7 minut, zchlaď a oloupej.",
      "Avokádo rozmačkej s citronem a solí, natři na opečený chléb.",
      "Navrch cottage, půlky cherry rajčat a vejce.",
    ],
  },
  {
    id: "b6",
    typ: "snidane",
    chut: "sladke",
    nazev: "Ovesná kaše s jogurtem a lesním ovocem",
    cas: 10,
    kcal: 450, bilkoviny: 33, sacharidy: 52, tuky: 12,
    shop: "Lidl",
    suroviny: [
      { n: "Ovesné vločky", q: 60, u: "g", cat: T },
      { n: "Mléko polotučné", q: 200, u: "ml", cat: D },
      { n: "Řecký jogurt 2 %", q: 150, u: "g", cat: D },
      { n: "Mražené lesní ovoce", q: 100, u: "g", cat: Z },
      { n: "Vlašské ořechy", q: 10, u: "g", cat: T },
      { n: "Skořice", q: 1, u: "g", cat: T },
    ],
    postup: [
      "Vločky vař v mléce 5 minut se špetkou soli a skořicí.",
      "Ovoce prohřej zvlášť, aby pustilo šťávu.",
      "Kaši zakápni jogurtem, přidej ovoce a ořechy.",
    ],
  },

  // ---------- SVAČINY ----------
  {
    id: "s1",
    typ: "svacina",
    chut: "slane",
    nazev: "Cottage s olivami a okurkou",
    cas: 3,
    kcal: 250, bilkoviny: 24, sacharidy: 12, tuky: 11,
    shop: "Lidl",
    suroviny: [
      { n: "Cottage sýr", q: 180, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Knäckebrot žitný", q: 20, u: "g", cat: P },
    ],
    postup: ["Cottage smíchej s nakrájenou okurkou a olivami, opepři, jez s knäckebrotem."],
  },
  {
    id: "s2",
    typ: "svacina",
    chut: "slane",
    nazev: "Hummus s mrkví a pita chlebem",
    cas: 5,
    kcal: 300, bilkoviny: 13, sacharidy: 36, tuky: 12,
    shop: "Rohlík",
    suroviny: [
      { n: "Hummus", q: 80, u: "g", cat: T },
      { n: "Mrkev", q: 120, u: "g", cat: Z },
      { n: "Pita celozrnná", q: 60, u: "g", cat: P },
    ],
    postup: ["Mrkev nakrájej na hranolky, pitu opeč a natrhej."],
  },
  {
    id: "s3",
    typ: "svacina",
    chut: "sladke",
    nazev: "Skyr s ořechy a jablkem",
    cas: 2,
    kcal: 280, bilkoviny: 28, sacharidy: 26, tuky: 8,
    shop: "Lidl",
    suroviny: [
      { n: "Skyr přírodní", q: 200, u: "g", cat: D },
      { n: "Jablko", q: 1, u: "ks", cat: Z },
      { n: "Mandle", q: 12, u: "g", cat: T },
    ],
    postup: ["Skyr smíchej s nastrouhaným jablkem a mandlemi."],
  },
  {
    id: "s4",
    typ: "svacina",
    chut: "slane",
    nazev: "Tuňákový salát v listech salátu",
    cas: 6,
    kcal: 260, bilkoviny: 30, sacharidy: 8, tuky: 12,
    shop: "Makro",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 120, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 50, u: "g", cat: D },
      { n: "Salát ledový / římský", q: 80, u: "g", cat: Z },
      { n: "Červená cibule", q: 20, u: "g", cat: Z },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: ["Tuňáka slij, smíchej s jogurtem, cibulí a citronem. Nandej do listů salátu."],
  },
  {
    id: "s5",
    typ: "svacina",
    chut: "sladke",
    nazev: "Kefír, pomeranč a hrst vlašských ořechů",
    cas: 2,
    kcal: 290, bilkoviny: 16, sacharidy: 28, tuky: 14,
    shop: "Lidl",
    suroviny: [
      { n: "Kefír / acidofilní mléko", q: 300, u: "ml", cat: D },
      { n: "Pomeranč", q: 1, u: "ks", cat: Z },
      { n: "Vlašské ořechy", q: 20, u: "g", cat: T },
    ],
    postup: ["Nic se nevaří. Jen nezapomeň, že ořechy jsou kalorická bomba — važ je."],
  },
  {
    id: "s6",
    typ: "svacina",
    chut: "slane",
    nazev: "Řecký jogurt s cizrnovými chipsy",
    cas: 4,
    kcal: 270, bilkoviny: 25, sacharidy: 24, tuky: 8,
    shop: "Rohlík",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 200, u: "g", cat: D },
      { n: "Cizrna konzerva", q: 80, u: "g", cat: T },
      { n: "Olivový olej", q: 3, u: "ml", cat: T },
      { n: "Rajčata cherry", q: 80, u: "g", cat: Z },
    ],
    postup: [
      "Cizrnu osuš, zakápni olejem, opeč 15 minut na 200 °C do křupava.",
      "Jogurt osol, opepři, navrch cizrna a rajčata.",
    ],
  },

  // ---------- OBĚDY ----------
  {
    id: "o1",
    typ: "obed",
    zdroj: "kure",
    nazev: "Kuřecí souvlaki s bulgurem a tzatziki",
    cas: 30,
    kcal: 620, bilkoviny: 55, sacharidy: 55, tuky: 19,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Bulgur", q: 70, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Okurka salátová", q: 80, u: "g", cat: Z },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Kuře nakrájej na kostky, marinuj v oleji, citronu, oreganu a česneku (klidně přes noc).",
      "Bulgur zalij vroucí vodou 1:2, přiklop na 15 minut.",
      "Kuře opeč na rozpálené pánvi 8 minut dokřupava.",
      "Tzatziki: nastrouhanou vymačkanou okurku smíchej s jogurtem a česnekem.",
    ],
  },
  {
    id: "o2",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Losos s quinoou a pečenou zeleninou",
    cas: 35,
    kcal: 650, bilkoviny: 45, sacharidy: 48, tuky: 28,
    shop: "Rohlík",
    suroviny: [
      { n: "Losos filet", q: 160, u: "g", cat: M },
      { n: "Quinoa", q: 60, u: "g", cat: T },
      { n: "Cuketa", q: 120, u: "g", cat: Z },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 40, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: [
      "Zeleninu nakrájej na větší kusy, promíchej s olejem a solí, peč 20 minut na 200 °C.",
      "Quinou propláchni a vař 12 minut ve dvojnásobku vody.",
      "Lososa přidej k zelenině na posledních 12 minut, kůží nahoru.",
      "Zakápni citronem.",
    ],
  },
  {
    id: "o3",
    typ: "obed",
    zdroj: "kure",
    nazev: "Gyros bowl s cizrnou a fetou",
    cas: 25,
    kcal: 640, bilkoviny: 52, sacharidy: 52, tuky: 22,
    shop: "Lidl",
    suroviny: [
      { n: "Kuřecí stehenní maso bez kosti", q: 170, u: "g", cat: M },
      { n: "Cizrna konzerva", q: 150, u: "g", cat: T },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Okurka salátová", q: 80, u: "g", cat: Z },
      { n: "Feta", q: 30, u: "g", cat: D },
      { n: "Rýže basmati", q: 40, u: "g", cat: T },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Gyros koření", q: 5, u: "g", cat: T },
    ],
    postup: [
      "Maso nakrájej na nudličky, obal v koření, opeč dosucha na pánvi.",
      "Rýži uvař, cizrnu prohřej s masem na konci.",
      "Do misky rýže, maso, syrová zelenina, feta.",
    ],
  },
  {
    id: "o4",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Fazolový salát s tuňákem a vejcem",
    cas: 15,
    kcal: 560, bilkoviny: 48, sacharidy: 42, tuky: 20,
    shop: "Makro",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 140, u: "g", cat: T },
      { n: "Bílé fazole konzerva", q: 180, u: "g", cat: T },
      { n: "Vejce M", q: 1, u: "ks", cat: D },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Petržel natě", q: 10, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Fazole propláchni, smíchej s tuňákem, rajčaty a cibulí.",
      "Zalij olejem s citronem, přidej petržel.",
      "Navrch půlené vejce, k tomu chléb.",
    ],
  },
  {
    id: "o5",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Krevety s cizrnovým salátem a fetou",
    cas: 20,
    kcal: 570, bilkoviny: 46, sacharidy: 40, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Krevety loupané mražené", q: 200, u: "g", cat: M },
      { n: "Cizrna konzerva", q: 160, u: "g", cat: T },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Krevety rozmrazené osuš, opeč na oleji s česnekem 3 minuty z každé strany.",
      "Smíchej s cizrnou a rajčaty, zakápni citronem, rozdrob fetu.",
    ],
  },
  {
    id: "o6",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Celozrnné těstoviny s tuňákem a olivami",
    cas: 20,
    kcal: 630, bilkoviny: 45, sacharidy: 68, tuky: 18,
    shop: "Lidl",
    suroviny: [
      { n: "Celozrnné těstoviny", q: 80, u: "g", cat: T },
      { n: "Tuňák ve vlastní šťávě", q: 140, u: "g", cat: T },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Parmazán", q: 10, u: "g", cat: D },
    ],
    postup: [
      "Těstoviny vař al dente.",
      "Na oleji orestuj česnek, přidej rajčata a olivy, vař 8 minut.",
      "Vmíchej tuňáka a hotové těstoviny, posyp parmazánem.",
    ],
  },
  {
    id: "o7",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Pečená makrela s bramborem a fazolkami",
    cas: 35,
    kcal: 660, bilkoviny: 44, sacharidy: 45, tuky: 32,
    shop: "Rohlík",
    suroviny: [
      { n: "Makrela celá / filet", q: 200, u: "g", cat: M },
      { n: "Brambory", q: 250, u: "g", cat: Z },
      { n: "Fazolky zelené mražené", q: 150, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Rozmarýn", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Brambory na měsíčky, olej, sůl, rozmarýn — peč 30 minut na 200 °C.",
      "Makrelu osol, naplň citronem, peč posledních 15 minut.",
      "Fazolky vař 5 minut, zakápni olejem.",
    ],
  },
  {
    id: "o8",
    typ: "obed",
    zdroj: "bezmase",
    nazev: "Cizrnový salát s grilovaným halloumi",
    cas: 20,
    kcal: 580, bilkoviny: 34, sacharidy: 45, tuky: 28,
    shop: "Lidl",
    suroviny: [
      { n: "Halloumi", q: 100, u: "g", cat: D },
      { n: "Cizrna konzerva", q: 180, u: "g", cat: T },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Olivový olej", q: 6, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Halloumi nakrájej na plátky a opeč nasucho z obou stran.",
      "Zeleninu s cizrnou zamíchej s olejem a citronem, navrch sýr.",
    ],
  },

  // ---------- VEČEŘE ----------
  {
    id: "v1",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Řecká pečená treska plaki",
    cas: 35,
    kcal: 480, bilkoviny: 48, sacharidy: 30, tuky: 17,
    shop: "Rohlík",
    suroviny: [
      { n: "Treska filet", q: 200, u: "g", cat: M },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Cibule", q: 60, u: "g", cat: Z },
      { n: "Brambory", q: 150, u: "g", cat: Z },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Petržel natě", q: 10, u: "g", cat: Z },
    ],
    postup: [
      "Na oleji zesklovatěj cibuli s česnekem, přidej rajčata, vař 10 minut.",
      "Do zapékací mísy dej tenké plátky brambor, na ně rybu a omáčku.",
      "Peč 25 minut na 190 °C, posyp petrželí.",
    ],
  },
  {
    id: "v2",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Krůtí kofta s tzatziki a salátem",
    cas: 30,
    kcal: 520, bilkoviny: 52, sacharidy: 24, tuky: 24,
    shop: "Makro",
    suroviny: [
      { n: "Mleté krůtí maso", q: 200, u: "g", cat: M },
      { n: "Řecký jogurt 2 %", q: 120, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Pita celozrnná", q: 30, u: "g", cat: P },
      { n: "Kmín mletý", q: 2, u: "g", cat: T },
      { n: "Olivový olej", q: 6, u: "ml", cat: T },
    ],
    postup: [
      "Maso smíchej s cibulí, kmínem, solí, vytvaruj podlouhlé placky.",
      "Opeč na pánvi 10 minut, průběžně otáčej.",
      "Tzatziki z jogurtu a vymačkané okurky, k tomu salát a kousek pity.",
    ],
  },
  {
    id: "v3",
    typ: "vecere",
    zdroj: "maso",
    nazev: "Zapečený lilek s mletým hovězím a jogurtem",
    cas: 45,
    kcal: 560, bilkoviny: 46, sacharidy: 26, tuky: 30,
    shop: "Rohlík",
    suroviny: [
      { n: "Mleté hovězí 10 %", q: 180, u: "g", cat: M },
      { n: "Lilek", q: 250, u: "g", cat: Z },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Parmazán", q: 15, u: "g", cat: D },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Skořice", q: 1, u: "g", cat: T },
    ],
    postup: [
      "Lilek na plátky, potři olejem, peč 15 minut na 200 °C.",
      "Maso orestuj s cibulí, přidej rajčata a špetku skořice, vař 10 minut.",
      "Vrstvi lilek a maso, navrch jogurt s parmazánem, zapeč 15 minut.",
    ],
  },
  {
    id: "v4",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Kuřecí prsa s cuketou, rajčaty a fetou",
    cas: 25,
    kcal: 490, bilkoviny: 54, sacharidy: 16, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 200, u: "g", cat: M },
      { n: "Cuketa", q: 200, u: "g", cat: Z },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
    ],
    postup: [
      "Kuře nařízni na motýlka, osol, opeč 4 minuty z každé strany.",
      "Přidej cuketu na půlměsíčky a rajčata, orestuj 6 minut.",
      "Posyp fetou a oreganem, přiklop na 2 minuty.",
    ],
  },
  {
    id: "v5",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Krevety saganaki s fetou a rajčaty",
    cas: 25,
    kcal: 450, bilkoviny: 42, sacharidy: 22, tuky: 21,
    shop: "Makro",
    suroviny: [
      { n: "Krevety loupané mražené", q: 200, u: "g", cat: M },
      { n: "Krájená rajčata konzerva", q: 200, u: "g", cat: T },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Na oleji orestuj česnek, přilij rajčata, vař 10 minut.",
      "Vlož krevety, po 4 minutách rozdrob fetu a přiklop.",
      "Vytírej chlebem.",
    ],
  },
  {
    id: "v6",
    typ: "vecere",
    zdroj: "bezmase",
    nazev: "Čočka s pečenou zeleninou a sázeným vejcem",
    cas: 35,
    kcal: 520, bilkoviny: 32, sacharidy: 55, tuky: 18,
    shop: "Lidl",
    suroviny: [
      { n: "Čočka beluga / zelená", q: 80, u: "g", cat: T },
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Cuketa", q: 150, u: "g", cat: Z },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 40, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Ocet balsamico", q: 5, u: "ml", cat: T },
    ],
    postup: [
      "Čočku vař 20 minut do měkka, sceď.",
      "Zeleninu peč 20 minut na 200 °C s olejem.",
      "Smíchej, zakápni balsamikem, navrch sázená vejce.",
    ],
  },
  {
    id: "v7",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Treska se špenátem a bramborovým pyré",
    cas: 30,
    kcal: 500, bilkoviny: 48, sacharidy: 38, tuky: 16,
    shop: "Rohlík",
    suroviny: [
      { n: "Treska filet", q: 200, u: "g", cat: M },
      { n: "Brambory", q: 220, u: "g", cat: Z },
      { n: "Špenát čerstvý", q: 150, u: "g", cat: Z },
      { n: "Mléko polotučné", q: 50, u: "ml", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: [
      "Brambory uvař, rozšťouchej s mlékem a lžičkou oleje.",
      "Rybu osol, opeč 3–4 minuty z každé strany, zakápni citronem.",
      "Špenát krátce zavadni s česnekem.",
    ],
  },
  {
    id: "v8",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Řecký salát s kuřetem a bílým jogurtem",
    cas: 20,
    kcal: 470, bilkoviny: 50, sacharidy: 18, tuky: 21,
    shop: "Lidl",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Rajčata", q: 150, u: "g", cat: Z },
      { n: "Okurka salátová", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Kuře opeč na grilovací pánvi, nech odpočinout a nakrájej.",
      "Zeleninu nakrájej nahrubo, zalij olejem, posyp oreganem a fetou.",
    ],
  },

  // ---------- SNÍDANĚ (2. série) ----------
  {
    id: "b7",
    typ: "snidane",
    chut: "sladke",
    nazev: "Skyr s medem, fíky a mandlemi",
    cas: 4,
    kcal: 420, bilkoviny: 38, sacharidy: 45, tuky: 10,
    shop: "Lidl",
    suroviny: [
      { n: "Skyr přírodní", q: 250, u: "g", cat: D },
      { n: "Sušené fíky", q: 40, u: "g", cat: T },
      { n: "Mandle", q: 15, u: "g", cat: T },
      { n: "Med", q: 10, u: "g", cat: T },
    ],
    postup: ["Fíky nakrájej na kolečka.", "Zamíchej do skyru s medem, posyp sekanými mandlemi."],
  },
  {
    id: "b8",
    typ: "snidane",
    chut: "slane",
    nazev: "Míchaná vejce s rajčaty a tvrdým sýrem",
    cas: 10,
    kcal: 440, bilkoviny: 33, sacharidy: 26, tuky: 24,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Rajčata", q: 150, u: "g", cat: Z },
      { n: "Eidam 30 %", q: 30, u: "g", cat: D },
      { n: "Chléb celozrnný", q: 50, u: "g", cat: P },
      { n: "Olivový olej", q: 6, u: "ml", cat: T },
    ],
    postup: [
      "Rajčata orestuj na oleji 4 minuty, dokud se nerozpadnou.",
      "Zalij vejci, míchej na mírném ohni, na konci vmíchej sýr.",
    ],
  },
  {
    id: "b9",
    typ: "snidane",
    chut: "slane",
    nazev: "Tvarohová pomazánka s okurkou na knäckebrotu",
    cas: 6,
    kcal: 390, bilkoviny: 36, sacharidy: 34, tuky: 12,
    shop: "Lidl",
    suroviny: [
      { n: "Tvaroh polotučný", q: 200, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Knäckebrot žitný", q: 45, u: "g", cat: P },
      { n: "Pažitka", q: 8, u: "g", cat: Z },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: ["Tvaroh utři s olejem a solí.", "Přidej nastrouhanou okurku a pažitku, namaž na plátky."],
  },
  {
    id: "b10",
    typ: "snidane",
    chut: "sladke",
    nazev: "Jogurtová mísa s banánem a arašídovým máslem",
    cas: 4,
    kcal: 470, bilkoviny: 33, sacharidy: 48, tuky: 16,
    shop: "Rohlík",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 250, u: "g", cat: D },
      { n: "Banán", q: 1, u: "ks", cat: Z },
      { n: "Arašídové máslo 100 %", q: 15, u: "g", cat: T },
      { n: "Ovesné vločky", q: 30, u: "g", cat: T },
    ],
    postup: ["Jogurt s vločkami do misky.", "Navrch kolečka banánu a rozehřáté arašídové máslo."],
  },
  {
    id: "b11",
    typ: "snidane",
    chut: "slane",
    nazev: "Pečená vejce s fetou a špenátem ve formičce",
    cas: 18,
    kcal: 400, bilkoviny: 34, sacharidy: 18, tuky: 22,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Špenát čerstvý", q: 100, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: [
      "Do vymazané zapékací misky dej špenát, rozklepni vejce, rozdrob fetu.",
      "Peč 12 minut na 180 °C, podávej s chlebem.",
    ],
  },
  {
    id: "b12",
    typ: "snidane",
    chut: "slane",
    nazev: "Cizrnová omeleta s rajčaty (bez masa)",
    cas: 15,
    kcal: 420, bilkoviny: 26, sacharidy: 44, tuky: 15,
    shop: "Rohlík",
    suroviny: [
      { n: "Cizrnová mouka", q: 70, u: "g", cat: T },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Mouku rozšlehej se 150 ml vody a solí, nech 5 minut odpočinout.",
      "Vylij na pánev s olejem, posyp rajčaty a fetou, peč 8 minut pod poklicí.",
    ],
  },

  // ---------- SVAČINY (2. série) ----------
  {
    id: "s7",
    typ: "svacina",
    chut: "slane",
    nazev: "Vejce natvrdo s cherry rajčaty",
    cas: 10,
    kcal: 230, bilkoviny: 20, sacharidy: 8, tuky: 13,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Cottage sýr", q: 80, u: "g", cat: D },
    ],
    postup: ["Vejce vař 9 minut, zchlaď.", "Podávej s rajčaty a cottage, osol a opepři."],
  },
  {
    id: "s8",
    typ: "svacina",
    chut: "slane",
    nazev: "Tzatziki s celozrnným knäckebrotem",
    cas: 8,
    kcal: 240, bilkoviny: 18, sacharidy: 24, tuky: 8,
    shop: "Rohlík",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 150, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
      { n: "Knäckebrot žitný", q: 30, u: "g", cat: P },
    ],
    postup: ["Okurku nastrouhej a vymačkej.", "Smíchej s jogurtem a česnekem, osol."],
  },
  {
    id: "s9",
    typ: "svacina",
    chut: "sladke",
    nazev: "Meloun s fetou a mátou",
    cas: 5,
    kcal: 220, bilkoviny: 12, sacharidy: 26, tuky: 9,
    shop: "Rohlík",
    suroviny: [
      { n: "Meloun vodní", q: 300, u: "g", cat: Z },
      { n: "Feta", q: 50, u: "g", cat: D },
      { n: "Máta čerstvá", q: 5, u: "g", cat: Z },
    ],
    postup: ["Meloun nakrájej na kostky, promíchej s fetou a natrhanou mátou."],
  },
  {
    id: "s10",
    typ: "svacina",
    chut: "sladke",
    nazev: "Proteinový jogurt s ořechy a skořicí",
    cas: 2,
    kcal: 260, bilkoviny: 30, sacharidy: 18, tuky: 8,
    shop: "Lidl",
    suroviny: [
      { n: "Bílý jogurt vysokoproteinový", q: 250, u: "g", cat: D },
      { n: "Vlašské ořechy", q: 12, u: "g", cat: T },
      { n: "Skořice", q: 1, u: "g", cat: T },
      { n: "Med", q: 5, u: "g", cat: T },
    ],
    postup: ["Zamíchej dohromady. Rychlejší jídlo v téhle appce nenajdeš."],
  },
  {
    id: "s11",
    typ: "svacina",
    chut: "slane",
    nazev: "Sardinky na knäckebrotu s citronem",
    cas: 5,
    kcal: 290, bilkoviny: 26, sacharidy: 20, tuky: 13,
    shop: "Makro",
    suroviny: [
      { n: "Sardinky v oleji", q: 100, u: "g", cat: T },
      { n: "Knäckebrot žitný", q: 30, u: "g", cat: P },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
      { n: "Červená cibule", q: 20, u: "g", cat: Z },
    ],
    postup: ["Sardinky sceď, rozprostři na plátky, zakápni citronem, posyp cibulí."],
  },
  {
    id: "s12",
    typ: "svacina",
    chut: "sladke",
    nazev: "Řecký jogurt s jahodami a pistáciemi",
    cas: 3,
    kcal: 280, bilkoviny: 26, sacharidy: 24, tuky: 10,
    shop: "Lidl",
    suroviny: [
      { n: "Řecký jogurt 2 %", q: 220, u: "g", cat: D },
      { n: "Jahody (i mražené)", q: 120, u: "g", cat: Z },
      { n: "Pistácie nesolené", q: 12, u: "g", cat: T },
    ],
    postup: ["Jahody nakrájej, zamíchej do jogurtu, posyp pistáciemi."],
  },

  // ---------- OBĚDY (2. série) ----------
  {
    id: "o9",
    typ: "obed",
    zdroj: "kure",
    nazev: "Kuřecí salát s bulgurem a bylinkami",
    cas: 20,
    kcal: 590, bilkoviny: 52, sacharidy: 52, tuky: 17,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Bulgur", q: 65, u: "g", cat: T },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Petržel natě", q: 15, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Bulgur zalij vroucí vodou, nech 15 minut nabobtnat.",
      "Kuře opeč a nakrájej, smíchej se zeleninou, bylinkami, olejem a citronem.",
    ],
  },
  {
    id: "o10",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Tuňákové wrapy s jogurtovým dresinkem",
    cas: 12,
    kcal: 560, bilkoviny: 45, sacharidy: 50, tuky: 18,
    shop: "Rohlík",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 140, u: "g", cat: T },
      { n: "Tortilla celozrnná", q: 2, u: "ks", cat: P },
      { n: "Řecký jogurt 2 %", q: 60, u: "g", cat: D },
      { n: "Salát ledový / římský", q: 60, u: "g", cat: Z },
      { n: "Rajčata", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 20, u: "g", cat: Z },
    ],
    postup: ["Tuňáka smíchej s jogurtem, solí a pepřem.", "Naplň tortilly se zeleninou a zaroluj."],
  },
  {
    id: "o11",
    typ: "obed",
    zdroj: "bezmase",
    nazev: "Čočkový salát s fetou a rajčaty",
    cas: 25,
    kcal: 560, bilkoviny: 32, sacharidy: 58, tuky: 20,
    shop: "Lidl",
    suroviny: [
      { n: "Čočka beluga / zelená", q: 90, u: "g", cat: T },
      { n: "Feta", q: 50, u: "g", cat: D },
      { n: "Rajčata cherry", q: 150, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Ocet balsamico", q: 5, u: "ml", cat: T },
    ],
    postup: ["Čočku vař 20 minut, sceď a nech vychladnout.", "Smíchej se zeleninou, olejem a octem, navrch feta."],
  },
  {
    id: "o12",
    typ: "obed",
    zdroj: "kure",
    nazev: "Kuřecí kebab s cizrnovým pyré",
    cas: 30,
    kcal: 620, bilkoviny: 54, sacharidy: 45, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 190, u: "g", cat: M },
      { n: "Cizrna konzerva", q: 200, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 60, u: "g", cat: D },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Paprika mletá sladká", q: 3, u: "g", cat: T },
    ],
    postup: [
      "Kuře nakrájej na kostky, okoření a opeč dokřupava.",
      "Cizrnu rozmixuj s jogurtem, česnekem, citronem a olejem do hladkého pyré.",
    ],
  },
  {
    id: "o13",
    typ: "obed",
    zdroj: "kure",
    nazev: "Zapečené kuře s bramborem a citronem",
    cas: 45,
    kcal: 640, bilkoviny: 52, sacharidy: 50, tuky: 24,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí stehenní maso bez kosti", q: 190, u: "g", cat: M },
      { n: "Brambory", q: 280, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Oregano sušené", q: 3, u: "g", cat: T },
    ],
    postup: [
      "Všechno naskládej do pekáče, zalij šťávou z citronu a 100 ml vody.",
      "Peč 40 minut na 200 °C, v půlce promíchej.",
    ],
  },
  {
    id: "o14",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Tuňákový salát s bramborem a fazolkami",
    cas: 25,
    kcal: 570, bilkoviny: 44, sacharidy: 48, tuky: 20,
    shop: "Lidl",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 140, u: "g", cat: T },
      { n: "Brambory", q: 250, u: "g", cat: Z },
      { n: "Fazolky zelené mražené", q: 150, u: "g", cat: Z },
      { n: "Vejce M", q: 1, u: "ks", cat: D },
      { n: "Olivy kalamata", q: 25, u: "g", cat: T },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: ["Brambory a fazolky uvař.", "Vlažné smíchej s tuňákem, olivami a olejem, navrch vejce."],
  },
  {
    id: "o15",
    typ: "obed",
    zdroj: "kure",
    nazev: "Krůtí nudličky s rýží a grilovanou zeleninou",
    cas: 25,
    kcal: 610, bilkoviny: 55, sacharidy: 58, tuky: 15,
    shop: "Makro",
    suroviny: [
      { n: "Krůtí prsa", q: 190, u: "g", cat: M },
      { n: "Rýže basmati", q: 70, u: "g", cat: T },
      { n: "Cuketa", q: 150, u: "g", cat: Z },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: ["Rýži uvař.", "Maso a zeleninu opeč na grilovací pánvi, dochuť oreganem a solí."],
  },
  {
    id: "o16",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Bílé fazole s rajčaty a tuňákem v troubě",
    cas: 30,
    kcal: 580, bilkoviny: 45, sacharidy: 50, tuky: 18,
    shop: "Rohlík",
    suroviny: [
      { n: "Bílé fazole konzerva", q: 200, u: "g", cat: T },
      { n: "Tuňák ve vlastní šťávě", q: 120, u: "g", cat: T },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
    ],
    postup: [
      "Cibuli orestuj, přidej rajčata a fazole, přendej do zapékací misky.",
      "Peč 20 minut na 190 °C, po vytažení vmíchej tuňáka.",
    ],
  },

  // ---------- VEČEŘE (2. série) ----------
  {
    id: "v9",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Losos z pánve s brokolicí",
    cas: 20,
    kcal: 490, bilkoviny: 44, sacharidy: 14, tuky: 28,
    shop: "Rohlík",
    suroviny: [
      { n: "Losos filet", q: 170, u: "g", cat: M },
      { n: "Brokolice", q: 250, u: "g", cat: Z },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Lososa peč na pánvi kůží dolů 5 minut, otoč na 2 minuty.",
      "Brokolici vař 4 minuty, promíchej s česnekem a olejem.",
    ],
  },
  {
    id: "v10",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Kuřecí souvlaki špízy se salátem",
    cas: 25,
    kcal: 480, bilkoviny: 52, sacharidy: 18, tuky: 21,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 200, u: "g", cat: M },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 50, u: "g", cat: Z },
      { n: "Salát ledový / římský", q: 80, u: "g", cat: Z },
      { n: "Řecký jogurt 2 %", q: 80, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: ["Maso a zeleninu napíchej na špejle.", "Peč 15 minut na 220 °C, otoč v půlce. Podávej s jogurtem a salátem."],
  },
  {
    id: "v11",
    typ: "vecere",
    zdroj: "bezmase",
    nazev: "Cuketové placky s jogurtovým dipem",
    cas: 25,
    kcal: 440, bilkoviny: 30, sacharidy: 32, tuky: 20,
    shop: "Lidl",
    suroviny: [
      { n: "Cuketa", q: 300, u: "g", cat: Z },
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Feta", q: 40, u: "g", cat: D },
      { n: "Mouka celozrnná", q: 40, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: [
      "Cuketu nastrouhej, osol a vymačkej vodu.",
      "Smíchej s vejci, moukou a fetou, smaž placky 3 minuty z každé strany.",
    ],
  },
  {
    id: "v12",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Kuřecí polévka s citronem a rýží (avgolemono light)",
    cas: 30,
    kcal: 420, bilkoviny: 44, sacharidy: 38, tuky: 10,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 170, u: "g", cat: M },
      { n: "Rýže basmati", q: 40, u: "g", cat: T },
      { n: "Vejce M", q: 1, u: "ks", cat: D },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Mrkev", q: 80, u: "g", cat: Z },
      { n: "Celer řapíkatý", q: 50, u: "g", cat: Z },
    ],
    postup: [
      "Kuře vař 15 minut s mrkví a celerem, maso vyndej a natrhej.",
      "Do vývaru dej rýži na 12 minut.",
      "Vejce rozšlehej s citronem, po lžících temperuj vývarem a vmíchej mimo oheň.",
    ],
  },
  {
    id: "v13",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Pečená treska s rajčaty a olivami",
    cas: 25,
    kcal: 430, bilkoviny: 46, sacharidy: 14, tuky: 20,
    shop: "Rohlík",
    suroviny: [
      { n: "Treska filet", q: 200, u: "g", cat: M },
      { n: "Rajčata cherry", q: 150, u: "g", cat: Z },
      { n: "Olivy kalamata", q: 30, u: "g", cat: T },
      { n: "Česnek", q: 1, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: ["Rybu polož do pekáčku, obsyp rajčaty, olivami a česnekem.", "Peč 18 minut na 200 °C."],
  },
  {
    id: "v14",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Plněné papriky s krůtím masem a rýží",
    cas: 45,
    kcal: 500, bilkoviny: 46, sacharidy: 42, tuky: 15,
    shop: "Lidl",
    suroviny: [
      { n: "Mleté krůtí maso", q: 180, u: "g", cat: M },
      { n: "Paprika červená", q: 2, u: "ks", cat: Z },
      { n: "Rýže basmati", q: 45, u: "g", cat: T },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
    ],
    postup: [
      "Maso orestuj s cibulí, smíchej s poloviční uvařenou rýží.",
      "Naplň papriky, zalij rajčaty, peč 30 minut na 190 °C pod fólií.",
    ],
  },
  {
    id: "v15",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Krevetový salát s avokádem a rukolou",
    cas: 15,
    kcal: 460, bilkoviny: 40, sacharidy: 16, tuky: 26,
    shop: "Makro",
    suroviny: [
      { n: "Krevety loupané mražené", q: 200, u: "g", cat: M },
      { n: "Avokádo", q: 0.5, u: "ks", cat: Z },
      { n: "Rukola", q: 60, u: "g", cat: Z },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: ["Krevety opeč 4 minuty.", "Smíchej s rukolou, avokádem a rajčaty, zakápni citronem a olejem."],
  },
  {
    id: "v16",
    typ: "vecere",
    zdroj: "maso",
    nazev: "Vepřová panenka se špenátem a fazolemi",
    cas: 30,
    kcal: 520, bilkoviny: 50, sacharidy: 32, tuky: 20,
    shop: "Makro",
    suroviny: [
      { n: "Vepřová panenka", q: 190, u: "g", cat: M },
      { n: "Bílé fazole konzerva", q: 180, u: "g", cat: T },
      { n: "Špenát čerstvý", q: 150, u: "g", cat: Z },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Rozmarýn", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Panenku opeč ze všech stran, dopeč 12 minut na 180 °C, nech odpočinout.",
      "Fazole prohřej s česnekem a špenátem, osol.",
    ],
  },

  // ---------- SNÍDANĚ (3. série) ----------
  {
    id: "b13",
    typ: "snidane",
    chut: "sladke",
    nazev: "Tvarohové lívance s borůvkami",
    cas: 15,
    kcal: 460, bilkoviny: 40, sacharidy: 45, tuky: 13,
    shop: "Lidl",
    suroviny: [
      { n: "Tvaroh polotučný", q: 200, u: "g", cat: D },
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Ovesné vločky", q: 40, u: "g", cat: T },
      { n: "Borůvky", q: 80, u: "g", cat: Z },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: [
      "Vločky rozmixuj na mouku, smíchej s tvarohem a vejci.",
      "Smaž malé lívance 2 minuty z každé strany, podávej s borůvkami.",
    ],
  },
  {
    id: "b14",
    typ: "snidane",
    chut: "slane",
    nazev: "Vaječný wrap s fetou a špenátem",
    cas: 12,
    kcal: 470, bilkoviny: 34, sacharidy: 36, tuky: 21,
    shop: "Rohlík",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Tortilla celozrnná", q: 1, u: "ks", cat: P },
      { n: "Feta", q: 35, u: "g", cat: D },
      { n: "Špenát čerstvý", q: 60, u: "g", cat: Z },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: ["Vejce usmaž se špenátem.", "Nandej na tortillu, posyp fetou a zabal."],
  },
  {
    id: "b15",
    typ: "snidane",
    chut: "sladke",
    nazev: "Chia puding s jogurtem a mangem",
    cas: 5,
    kcal: 420, bilkoviny: 30, sacharidy: 40, tuky: 15,
    shop: "Rohlík",
    suroviny: [
      { n: "Chia semínka", q: 25, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 200, u: "g", cat: D },
      { n: "Mléko polotučné", q: 100, u: "ml", cat: D },
      { n: "Mango (i mražené)", q: 100, u: "g", cat: Z },
    ],
    postup: [
      "Chia zalij mlékem, nech přes noc v lednici.",
      "Ráno navrství s jogurtem a mangem.",
    ],
  },
  {
    id: "b16",
    typ: "snidane",
    chut: "slane",
    nazev: "Cottage toast s rajčaty a oreganem",
    cas: 7,
    kcal: 400, bilkoviny: 32, sacharidy: 38, tuky: 12,
    shop: "Lidl",
    suroviny: [
      { n: "Chléb celozrnný", q: 70, u: "g", cat: P },
      { n: "Cottage sýr", q: 180, u: "g", cat: D },
      { n: "Rajčata", q: 150, u: "g", cat: Z },
      { n: "Olivový olej", q: 6, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: ["Chléb opeč, natři cottage.", "Navrch plátky rajčat, olej, oregano, sůl."],
  },
  {
    id: "b17",
    typ: "snidane",
    chut: "slane",
    nazev: "Omeleta s uzeným lososem a koprem",
    cas: 12,
    kcal: 450, bilkoviny: 38, sacharidy: 20, tuky: 24,
    shop: "Makro",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Uzený losos", q: 60, u: "g", cat: M },
      { n: "Kopr čerstvý", q: 5, u: "g", cat: Z },
      { n: "Chléb celozrnný", q: 40, u: "g", cat: P },
      { n: "Olivový olej", q: 5, u: "ml", cat: T },
    ],
    postup: ["Usmaž jemnou omeletu.", "Na hotovou dej lososa a kopr, přehni."],
  },
  {
    id: "b18",
    typ: "snidane",
    chut: "sladke",
    nazev: "Proteinová kaše s jablkem a skořicí",
    cas: 10,
    kcal: 440, bilkoviny: 35, sacharidy: 55, tuky: 9,
    shop: "Lidl",
    suroviny: [
      { n: "Ovesné vločky", q: 60, u: "g", cat: T },
      { n: "Mléko polotučné", q: 250, u: "ml", cat: D },
      { n: "Tvaroh polotučný", q: 120, u: "g", cat: D },
      { n: "Jablko", q: 1, u: "ks", cat: Z },
      { n: "Skořice", q: 1, u: "g", cat: T },
    ],
    postup: ["Vločky uvař v mléce.", "Vmíchej tvaroh, navrch dušené jablko se skořicí."],
  },

  // ---------- SVAČINY (3. série) ----------
  {
    id: "s13",
    typ: "svacina",
    chut: "sladke",
    nazev: "Broskev s cottage a medem",
    cas: 3,
    kcal: 250, bilkoviny: 24, sacharidy: 26, tuky: 6,
    shop: "Lidl",
    suroviny: [
      { n: "Cottage sýr", q: 180, u: "g", cat: D },
      { n: "Broskev (i kompot bez cukru)", q: 150, u: "g", cat: Z },
      { n: "Med", q: 8, u: "g", cat: T },
    ],
    postup: ["Broskev nakrájej, přidej k cottage a zakápni medem."],
  },
  {
    id: "s14",
    typ: "svacina",
    chut: "slane",
    nazev: "Tuňáková pomazánka na knäckebrotu",
    cas: 5,
    kcal: 280, bilkoviny: 30, sacharidy: 22, tuky: 9,
    shop: "Makro",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 120, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 60, u: "g", cat: D },
      { n: "Knäckebrot žitný", q: 30, u: "g", cat: P },
      { n: "Pažitka", q: 5, u: "g", cat: Z },
    ],
    postup: ["Tuňáka utři s jogurtem a pažitkou, namaž."],
  },
  {
    id: "s15",
    typ: "svacina",
    chut: "sladke",
    nazev: "Tvarohový krém s kakaem",
    cas: 4,
    kcal: 270, bilkoviny: 34, sacharidy: 20, tuky: 7,
    shop: "Lidl",
    suroviny: [
      { n: "Tvaroh polotučný", q: 200, u: "g", cat: D },
      { n: "Kakao 100 %", q: 8, u: "g", cat: T },
      { n: "Med", q: 10, u: "g", cat: T },
      { n: "Banán", q: 0.5, u: "ks", cat: Z },
    ],
    postup: ["Vyšlehej tvaroh s kakaem, medem a rozmačkaným banánem."],
  },
  {
    id: "s16",
    typ: "svacina",
    chut: "slane",
    nazev: "Řecké mezze: olivy, feta, rajčata, pita",
    cas: 5,
    kcal: 320, bilkoviny: 16, sacharidy: 28, tuky: 17,
    shop: "Rohlík",
    suroviny: [
      { n: "Feta", q: 60, u: "g", cat: D },
      { n: "Olivy kalamata", q: 30, u: "g", cat: T },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Pita celozrnná", q: 50, u: "g", cat: P },
    ],
    postup: ["Naaranžuj na prkénko, zakápni olejem, opeč pitu."],
  },
  {
    id: "s17",
    typ: "svacina",
    chut: "sladke",
    nazev: "Skyr s jablkem a arašídovým máslem",
    cas: 3,
    kcal: 300, bilkoviny: 28, sacharidy: 28, tuky: 10,
    shop: "Lidl",
    suroviny: [
      { n: "Skyr přírodní", q: 200, u: "g", cat: D },
      { n: "Jablko", q: 1, u: "ks", cat: Z },
      { n: "Arašídové máslo 100 %", q: 12, u: "g", cat: T },
    ],
    postup: ["Jablko nakrájej, smíchej se skyrem a máslem."],
  },
  {
    id: "s18",
    typ: "svacina",
    chut: "slane",
    nazev: "Vejce s avokádem a cherry rajčaty",
    cas: 10,
    kcal: 290, bilkoviny: 20, sacharidy: 10, tuky: 20,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 2, u: "ks", cat: D },
      { n: "Avokádo", q: 0.5, u: "ks", cat: Z },
      { n: "Rajčata cherry", q: 100, u: "g", cat: Z },
      { n: "Citron", q: 0.25, u: "ks", cat: Z },
    ],
    postup: ["Vejce uvař natvrdo.", "Podávej s avokádem, rajčaty a citronem."],
  },

  // ---------- OBĚDY (3. série) ----------
  {
    id: "o17",
    typ: "obed",
    zdroj: "bezmase",
    nazev: "Fasolada — řecká fazolová polévka",
    cas: 35,
    kcal: 520, bilkoviny: 26, sacharidy: 62, tuky: 18,
    shop: "Lidl",
    suroviny: [
      { n: "Bílé fazole konzerva", q: 250, u: "g", cat: T },
      { n: "Mrkev", q: 100, u: "g", cat: Z },
      { n: "Celer řapíkatý", q: 60, u: "g", cat: Z },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Olivový olej", q: 10, u: "ml", cat: T },
      { n: "Chléb celozrnný", q: 60, u: "g", cat: P },
    ],
    postup: [
      "Mrkev a celer orestuj na oleji.",
      "Přidej rajčata, fazole a 400 ml vody, vař 20 minut.",
      "Podávej s chlebem.",
    ],
  },
  {
    id: "o18",
    typ: "obed",
    zdroj: "bezmase",
    nazev: "Zapečená quinoa se zeleninou a fetou",
    cas: 35,
    kcal: 560, bilkoviny: 28, sacharidy: 58, tuky: 22,
    shop: "Rohlík",
    suroviny: [
      { n: "Quinoa", q: 80, u: "g", cat: T },
      { n: "Cuketa", q: 150, u: "g", cat: Z },
      { n: "Paprika červená", q: 100, u: "g", cat: Z },
      { n: "Feta", q: 60, u: "g", cat: D },
      { n: "Vejce M", q: 1, u: "ks", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: [
      "Quinou uvař, zeleninu orestuj.",
      "Smíchej s rozšlehaným vejcem, přendej do formy, posyp fetou.",
      "Zapeč 20 minut na 190 °C.",
    ],
  },
  {
    id: "o19",
    typ: "obed",
    zdroj: "bezmase",
    nazev: "Falafel bowl s tzatziki",
    cas: 30,
    kcal: 590, bilkoviny: 27, sacharidy: 60, tuky: 26,
    shop: "Lidl",
    suroviny: [
      { n: "Cizrna konzerva", q: 200, u: "g", cat: T },
      { n: "Bulgur", q: 50, u: "g", cat: T },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Petržel natě", q: 15, u: "g", cat: Z },
      { n: "Olivový olej", q: 10, u: "ml", cat: T },
      { n: "Kmín mletý", q: 3, u: "g", cat: T },
    ],
    postup: [
      "Cizrnu rozmixuj s petrželí, kmínem a solí, vytvaruj kuličky.",
      "Peč 20 minut na 200 °C, potřené olejem.",
      "Podávej s bulgurem a tzatziki.",
    ],
  },
  {
    id: "o20",
    typ: "obed",
    zdroj: "kure",
    nazev: "Kuřecí gyros v pitě",
    cas: 25,
    kcal: 640, bilkoviny: 52, sacharidy: 55, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Pita celozrnná", q: 80, u: "g", cat: P },
      { n: "Řecký jogurt 2 %", q: 80, u: "g", cat: D },
      { n: "Rajčata", q: 100, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Gyros koření", q: 5, u: "g", cat: T },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: ["Kuře v koření opeč dokřupava.", "Pitu nahřej, naplň masem, zeleninou a jogurtem."],
  },
  {
    id: "o21",
    typ: "obed",
    zdroj: "kure",
    nazev: "Kuřecí spanakorizo — rýže se špenátem",
    cas: 30,
    kcal: 600, bilkoviny: 50, sacharidy: 55, tuky: 18,
    shop: "Lidl",
    suroviny: [
      { n: "Kuřecí prsa", q: 180, u: "g", cat: M },
      { n: "Rýže basmati", q: 70, u: "g", cat: T },
      { n: "Špenát čerstvý", q: 200, u: "g", cat: Z },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: [
      "Kuře opeč a odlož, na stejné pánvi zesklovatěj cibuli.",
      "Přidej rýži, 200 ml vody a špenát, vař 15 minut.",
      "Vrať maso, zakápni citronem.",
    ],
  },
  {
    id: "o22",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Lososový bowl s quinoou a okurkou",
    cas: 25,
    kcal: 620, bilkoviny: 45, sacharidy: 48, tuky: 26,
    shop: "Rohlík",
    suroviny: [
      { n: "Losos filet", q: 160, u: "g", cat: M },
      { n: "Quinoa", q: 65, u: "g", cat: T },
      { n: "Okurka salátová", q: 120, u: "g", cat: Z },
      { n: "Avokádo", q: 0.5, u: "ks", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Sezamová semínka", q: 8, u: "g", cat: T },
    ],
    postup: ["Quinou uvař, lososa opeč.", "Poskládej do misky se zeleninou, posyp sezamem."],
  },
  {
    id: "o23",
    typ: "obed",
    zdroj: "ryba",
    nazev: "Tuňákové karbanátky s jogurtovou omáčkou",
    cas: 25,
    kcal: 560, bilkoviny: 48, sacharidy: 42, tuky: 20,
    shop: "Makro",
    suroviny: [
      { n: "Tuňák ve vlastní šťávě", q: 160, u: "g", cat: T },
      { n: "Brambory", q: 200, u: "g", cat: Z },
      { n: "Vejce M", q: 1, u: "ks", cat: D },
      { n: "Řecký jogurt 2 %", q: 80, u: "g", cat: D },
      { n: "Kopr čerstvý", q: 5, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: [
      "Brambory uvař a rozšťouchej, smíchej s tuňákem a vejcem.",
      "Vytvaruj karbanátky, opeč 3 minuty z každé strany.",
      "Podávej s jogurtem s koprem.",
    ],
  },
  {
    id: "o24",
    typ: "obed",
    zdroj: "maso",
    nazev: "Hovězí stifado s bramborem",
    cas: 45,
    kcal: 650, bilkoviny: 50, sacharidy: 48, tuky: 26,
    shop: "Makro",
    suroviny: [
      { n: "Hovězí zadní", q: 180, u: "g", cat: M },
      { n: "Cibule", q: 120, u: "g", cat: Z },
      { n: "Krájená rajčata konzerva", q: 150, u: "g", cat: T },
      { n: "Brambory", q: 220, u: "g", cat: Z },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Skořice", q: 1, u: "g", cat: T },
      { n: "Ocet balsamico", q: 8, u: "ml", cat: T },
    ],
    postup: [
      "Maso zprudka opeč, přidej cibuli a orestuj.",
      "Zalij rajčaty, octem, přidej skořici a dus 35 minut.",
      "Brambory uvař nebo upeč zvlášť.",
    ],
  },
  {
    id: "o25",
    typ: "obed",
    zdroj: "maso",
    nazev: "Vepřová souvlaki s pitou a salátem",
    cas: 30,
    kcal: 620, bilkoviny: 50, sacharidy: 45, tuky: 25,
    shop: "Makro",
    suroviny: [
      { n: "Vepřová panenka", q: 190, u: "g", cat: M },
      { n: "Pita celozrnná", q: 70, u: "g", cat: P },
      { n: "Rajčata", q: 120, u: "g", cat: Z },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Řecký jogurt 2 %", q: 70, u: "g", cat: D },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: [
      "Maso na kostky, marinuj v oleji, oreganu a citronu.",
      "Opeč na grilovací pánvi 8 minut.",
      "Podávej s nahřátou pitou, salátem a jogurtem.",
    ],
  },

  // ---------- VEČEŘE (3. série) ----------
  {
    id: "v17",
    typ: "vecere",
    zdroj: "bezmase",
    nazev: "Gigantes — pečené fazole s fetou",
    cas: 35,
    kcal: 480, bilkoviny: 26, sacharidy: 52, tuky: 18,
    shop: "Rohlík",
    suroviny: [
      { n: "Bílé fazole konzerva", q: 250, u: "g", cat: T },
      { n: "Krájená rajčata konzerva", q: 200, u: "g", cat: T },
      { n: "Cibule", q: 60, u: "g", cat: Z },
      { n: "Feta", q: 50, u: "g", cat: D },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Kopr čerstvý", q: 5, u: "g", cat: Z },
    ],
    postup: [
      "Cibuli orestuj, přidej rajčata a fazole.",
      "Přendej do zapékací misky, peč 20 minut na 200 °C.",
      "Posyp fetou a koprem.",
    ],
  },
  {
    id: "v18",
    typ: "vecere",
    zdroj: "bezmase",
    nazev: "Špenátovo-fetová omeleta se salátem",
    cas: 15,
    kcal: 420, bilkoviny: 32, sacharidy: 14, tuky: 26,
    shop: "Lidl",
    suroviny: [
      { n: "Vejce M", q: 3, u: "ks", cat: D },
      { n: "Špenát čerstvý", q: 120, u: "g", cat: Z },
      { n: "Feta", q: 50, u: "g", cat: D },
      { n: "Salát ledový / římský", q: 80, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
    ],
    postup: ["Špenát zavadni, zalij vejci.", "Posyp fetou, dopeč pod poklicí, podávej se salátem."],
  },
  {
    id: "v19",
    typ: "vecere",
    zdroj: "bezmase",
    nazev: "Halloumi s čočkou a pečenou paprikou",
    cas: 30,
    kcal: 540, bilkoviny: 34, sacharidy: 42, tuky: 26,
    shop: "Lidl",
    suroviny: [
      { n: "Halloumi", q: 100, u: "g", cat: D },
      { n: "Čočka beluga / zelená", q: 80, u: "g", cat: T },
      { n: "Paprika červená", q: 150, u: "g", cat: Z },
      { n: "Červená cibule", q: 30, u: "g", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Ocet balsamico", q: 5, u: "ml", cat: T },
    ],
    postup: ["Čočku uvař, papriku upeč.", "Halloumi opeč nasucho, poskládej a zakápni octem."],
  },
  {
    id: "v20",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Kuřecí stehna s citronem a oreganem",
    cas: 40,
    kcal: 520, bilkoviny: 48, sacharidy: 22, tuky: 26,
    shop: "Makro",
    suroviny: [
      { n: "Kuřecí stehenní maso bez kosti", q: 200, u: "g", cat: M },
      { n: "Brambory", q: 150, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Oregano sušené", q: 3, u: "g", cat: T },
    ],
    postup: ["Vše naskládej do pekáče.", "Peč 35 minut na 200 °C, v půlce promíchej."],
  },
  {
    id: "v21",
    typ: "vecere",
    zdroj: "kure",
    nazev: "Krůtí burger s tzatziki bez housky",
    cas: 25,
    kcal: 470, bilkoviny: 52, sacharidy: 18, tuky: 20,
    shop: "Makro",
    suroviny: [
      { n: "Mleté krůtí maso", q: 200, u: "g", cat: M },
      { n: "Řecký jogurt 2 %", q: 100, u: "g", cat: D },
      { n: "Okurka salátová", q: 100, u: "g", cat: Z },
      { n: "Rajčata", q: 100, u: "g", cat: Z },
      { n: "Salát ledový / římský", q: 60, u: "g", cat: Z },
      { n: "Olivový olej", q: 7, u: "ml", cat: T },
    ],
    postup: [
      "Z masa vytvaruj placky, opeč 5 minut z každé strany.",
      "Podávej v listech salátu s tzatziki a zeleninou.",
    ],
  },
  {
    id: "v22",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Pečený mořský vlk se zeleninou",
    cas: 30,
    kcal: 460, bilkoviny: 46, sacharidy: 18, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Mořský vlk (filet)", q: 200, u: "g", cat: M },
      { n: "Cuketa", q: 150, u: "g", cat: Z },
      { n: "Rajčata cherry", q: 120, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Rozmarýn", q: 2, u: "g", cat: T },
    ],
    postup: ["Zeleninu rozlož do pekáčku, navrch rybu.", "Peč 20 minut na 200 °C, zakápni citronem."],
  },
  {
    id: "v23",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Tuňákový steak se zelenými fazolkami",
    cas: 20,
    kcal: 470, bilkoviny: 50, sacharidy: 16, tuky: 22,
    shop: "Makro",
    suroviny: [
      { n: "Tuňákový steak", q: 180, u: "g", cat: M },
      { n: "Fazolky zelené mražené", q: 200, u: "g", cat: Z },
      { n: "Česnek", q: 2, u: "stroužek", cat: Z },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
    ],
    postup: [
      "Steak opeč 2 minuty z každé strany, uvnitř nech růžový.",
      "Fazolky vař 5 minut, prohoď na pánvi s česnekem.",
    ],
  },
  {
    id: "v24",
    typ: "vecere",
    zdroj: "ryba",
    nazev: "Pečené sardinky s citronem a bramborem",
    cas: 30,
    kcal: 540, bilkoviny: 44, sacharidy: 38, tuky: 24,
    shop: "Makro",
    suroviny: [
      { n: "Sardinky čerstvé / mražené", q: 220, u: "g", cat: M },
      { n: "Brambory", q: 220, u: "g", cat: Z },
      { n: "Citron", q: 0.5, u: "ks", cat: Z },
      { n: "Olivový olej", q: 9, u: "ml", cat: T },
      { n: "Oregano sušené", q: 2, u: "g", cat: T },
    ],
    postup: ["Brambory peč 25 minut.", "Sardinky přidej na posledních 12 minut, zakápni citronem."],
  },
  {
    id: "v25",
    typ: "vecere",
    zdroj: "maso",
    nazev: "Keftedes — hovězí kuličky v rajčatové omáčce",
    cas: 35,
    kcal: 540, bilkoviny: 48, sacharidy: 28, tuky: 26,
    shop: "Lidl",
    suroviny: [
      { n: "Mleté hovězí 10 %", q: 190, u: "g", cat: M },
      { n: "Krájená rajčata konzerva", q: 200, u: "g", cat: T },
      { n: "Cibule", q: 50, u: "g", cat: Z },
      { n: "Vejce M", q: 0.5, u: "ks", cat: D },
      { n: "Olivový olej", q: 8, u: "ml", cat: T },
      { n: "Máta čerstvá", q: 5, u: "g", cat: Z },
      { n: "Chléb celozrnný", q: 30, u: "g", cat: P },
    ],
    postup: [
      "Maso smíchej s cibulí, vejcem a mátou, vytvaruj kuličky.",
      "Opeč, zalij rajčaty a dus 15 minut.",
    ],
  },
];

export const TYPY = {
  snidane: "Snídaně",
  svacina: "Svačina",
  obed: "Oběd",
  vecere: "Večeře",
};

export const byId = (id) => RECIPES.find((r) => r.id === id);
export const byType = (t) => RECIPES.filter((r) => r.typ === t);

// Štítky pro filtrování v plánovači
export const STITKY = {
  sladke: "Sladké",
  slane: "Slané",
  bezmase: "Bezmasé",
  kure: "Kuře a krůta",
  ryba: "Ryby a plody moře",
  maso: "Červené maso",
};

export const STITKY_PRO_TYP = {
  snidane: ["sladke", "slane"],
  svacina: ["sladke", "slane"],
  obed: ["bezmase", "kure", "ryba", "maso"],
  vecere: ["bezmase", "kure", "ryba", "maso"],
};

export function stitek(r) {
  return r.chut || r.zdroj || null;
}
